---
title: "Copernicus_Med_MHW"
author: "Dan Bez Golanski"
date: "`r Sys.Date()`"
output: html_document
---
## Load packages
```{r warning=FALSE}
library(ncdf4)
library(lubridate)
library(tidyverse)
library(heatwaveR)
```
##Functions
```{r}
sst_copernicus_to_df <- function(coperniucs_nc) {
dim_lon <- ncvar_get(coperniucs_nc,"lon")
dim_lat <- ncvar_get(coperniucs_nc,"lat")
dim_time <- ncvar_get(coperniucs_nc,"time")
t_units <- ncatt_get(coperniucs_nc,"time","units") 
t_ustr <- strsplit(t_units$value, " ")
t_dstr <- strsplit(unlist(t_ustr)[3], "-")
sst <- ncvar_get(coperniucs_nc,"analysed_sst",collapse_degen = F)
# analysis_error <- ncvar_get(coperniucs_nc,"analysis_error",collapse_degen = F)
sst_wide <- as.matrix(expand.grid(dim_lon,dim_lat))
sst_wide <- as.data.frame(sst_wide)
names(sst_wide) <- c("lon","lat")
sst_wide <- sst_wide %>% arrange(lon)
for (year_i in 1:length(dim_time)) {
  temp_date <-sst[,,year_i] 
  temp_date <- t(temp_date)
  vec_temp_date <- c(temp_date)
  sst_wide[,year_i+2] <- vec_temp_date
}
names(sst_wide) <- c("lon","lat",dim_time)
sst_long <- cbind(sst_wide[1:2], stack(sst_wide[3:dim(sst_wide)[2]]))
names(sst_long) <- c("lon","lat","sst","date")
sst_long <- na.omit(sst_long)
sst_long$date <- as.numeric(as.character(sst_long$date))
sst_long$date <- ymd(t_dstr)+ dseconds(sst_long$date)
sst_long$sst <- sst_long$sst - 273.15
return(sst_long)
}
```

##Load data
```{r}
sst_long_med<- readRDS("Med/Coper_SST_Med.RDS")
sst_long_red<- readRDS("Red Sea/Coper_SST_Red.RDS")
```

##Load ncdf
```{r}
med_coperniucs_nc <- nc_open("Med/Israel Climtology/cmems_SST_MED_SST_L4_REP_OBSERVATIONS_010_021_1701005428241.nc")
red_copernicus_nc <- nc_open("Red Sea/Eilat climetology/METOFFICE-GLO-SST-L4-REP-OBS-SST_1705328292068.nc")

```

##Create dataframe
```{r}
med_sst_long <- sst_copernicus_to_df(med_coperniucs_nc)
red_sst_long <- sst_copernicus_to_df(red_copernicus_nc)
saveRDS(med_sst_long,"Coper_SST_Med.RDS")
saveRDS(red_sst_long,"Coper_SST_Red.RDS")
```

##Calculate climatelogy fow whole med and MHW's events
```{r} 
coordinates_list <- sst_long_med %>% filter(date==sst_long$date[1])
coordinates_list <- coordinates_list %>% select(lat,lon)
MHW_med <- data.frame(lat=double(),
                      lon=double(),
                      date_start=Date(),
                      date_end=Date(),
                      duration=double(),
                      intensity_mean=double(),
                      intensity_max=double(),
                      intensity_cumulative=double(),
                      rate_onset=double(),
                      rate_decline=double()
)
for (coord_num in 1:dim(coordinates_list)[1]) {
  temp_point <- sst_long %>% filter(lat==coordinates_list$lat[coord_num] &coordinates_list$lon[coord_num])
  #deleting lat and lon cause all in same position
  temp_point <- temp_point[-1:-2]
  temp_point <- temp_point %>% arrange(date)

  names(temp_point) <- c("temp","t")
  clim_period <- c(temp_point$t[1],"2011-08-25")
  MHW_climatelogy_tresh <- ts2clm(temp_point,climatologyPeriod = clim_period,pctile = 90)
  # MCS_climatelogy_tresh <- ts2clm(temp_point,climatologyPeriod = clim_period,pctile = 10)
  MHW_events <- detect_event(MHW_climatelogy_tresh)
  MHW_events <- MHW_events$event %>%    select(duration,date_start,date_end,intensity_mean,intensity_max,intensity_cumulative,rate_onset,rate_decline)
  # MCS_events <- detect_event(MCS_climatelogy_tresh,coldSpells = T)
  MHW_events$lat <- coordinates_list$lat[coord_num]
  MHW_events$lon <- coordinates_list$lon[coord_num]  
  MHW_med <- rbind(MHW_med,MHW_events)
  print(coord_num)
}
MHW_med$year <- format(MHW_med$date_start,"%Y")
saveRDS(MHW_med,"MHW_Events_Isr_Med_allpoints.RDS")
write.csv(MHW_med,"MHW_Events_Isr_Med_allpoints.csv")

```

##MHW Isr_med_statistics_allpoints
```{r}
#Statistics for Israeli coast 
MHW_med_sum_year_date_start <- MHW_med %>% group_by(year,date_start,duration) %>% summarise(Coord_num=n(),avg_mean_intensity=mean(intensity_mean),avg_max_intensity=mean(intensity_max),avg_intensity_cummelative=mean(intensity_cumulative),avg_onset_rate=mean(rate_onset),avg_decline_rate=mean(rate_decline))
MHW_med_sum_year_date_start$area_ratio <- MHW_med_sum_year_date_start$Coord_num/1443
MHW_med_spatial_filter <- MHW_med_sum_year_date_start[MHW_med_sum_year_date_start$area_ratio>0.2,]
write.csv(MHW_med_spatial_filter,"Isr_MHW_Med_0.2_area_filter.csv")

```


##compute marine heat waves for the whole israeli coast mean sst
```{r}
mean_Isr_coast <- sst_long %>% group_by(date) %>% summarise(mean_sst=mean(sst))
clim_period <- c(mean_Isr_coast$date[1],"2011-08-25")
names(mean_Isr_coast) <- c("t","temp")
MHW_climatelogy_tresh <- ts2clm(mean_Isr_coast,climatologyPeriod = clim_period,pctile = 90)
# MCS_climatelogy_tresh <- ts2clm(temp_point,climatologyPeriod = clim_period,pctile = 10)
MHW_events <- detect_event(MHW_climatelogy_tresh)
event_line(MHW_events)
MHW_events <- MHW_events$event %>%    select(duration,date_start,date_end,intensity_mean,intensity_max,intensity_cumulative,rate_onset,rate_decline)
write.csv(MHW_events,"MHW_Events_ISR_mean")
```

##Calculate climatelogy for red sea and MHW's events
```{r} 
sst_long_red <- sst_long_red %>% filter(lat == sst_long_red$lat[1])
sst_long_red <- sst_long_red %>%  select(-lat,-lon)
sst_long_red <- sst_long_red %>% arrange(date)
sst_long_red$date <- as.Date(sst_long_red$date)
names(sst_long_red) <- c("temp","t")
clim_period <- c(sst_long_red$t[1],"2011-08-25")
MHW_climatelogy_tresh <- ts2clm(sst_long_red,climatologyPeriod = clim_period,pctile = 90)
# MCS_climatelogy_tresh <- ts2clm(temp_point,climatologyPeriod = clim_period,pctile = 10)
MHW_events <- detect_event(MHW_climatelogy_tresh)
MHW_events <- MHW_events$event %>%    select(duration,date_start,date_end,intensity_mean,intensity_max,intensity_cumulative,rate_onset,rate_decline)
# MCS_events <- detect_event(MCS_climatelogy_tresh,coldSpells = T)
write.csv(MHW_events,"MHW_Events_RedSea.csv")
event_line(MHW_events,)
```
