---
title: "MHW_eilat_DBG"
author: "Dan Bez Golanski"
date: "2023-11-01"
output: html_document
---
#load packages
```{r warning=FALSE}
library(tidyverse)
library(patchwork)
library(lubridate)
library(suncalc)
```


#load data
```{r}
fish_df <- readRDS("tracking data - linear array with meta and displacement.RDS")

filter_fish <-  readRDS("Valuble_fish.RDS")
```

#filter valuble_fish and compute sampling time frequncies
```{r}
valuble_fish <- c(1255785,1255787,1255788,1255789,1255791,1255800,1255801,1255803,1255805,1255806,1255807,1255809,1255810,1255811,1255812,1255814,1255815)
filter_fish <- fish_df %>% filter(fish_id %in% valuble_fish)
filter_fish <- filter_fish %>%
  select(-fish_temperature) %>% 
  arrange(fish_id,real_datetime)
filter_fish$date <- as.Date(filter_fish$real_datetime,format = "%d/%m/%y")
samp_freq_df <- data.frame(fish_id=integer(),
                           date=POSIXct(),
                           mean_freq_min=double(),
                           median_freq_min=double(),
                           n=integer())
for (fish in valuble_fish) {
  temp_fish <- filter_fish %>% filter(fish_id==fish)
  for (day in unique(temp_fish$date)) {
    temp_day <- temp_fish %>% filter(date==day)
    freq_vector <- c()
    for (row_num in 2:dim(temp_day)[1]) {
      freq_vector[row_num-1] <- difftime(temp_day$real_datetime[row_num],temp_day$real_datetime[row_num-1],units = "mins")
      
    }
    temp_samp_df <- data.frame(fish_id=fish,
                                 date=day,
                                 mean_freq_min = mean(freq_vector),
                                 median_freq_min= median(freq_vector),
                                 n=length(freq_vector))
    samp_freq_df <- rbind(samp_freq_df,temp_samp_df)
  }
  
}
rm(temp_day,temp_fish,temp_samp_df)
write.csv(samp_freq_df,"fish_sampling_frequences.csv")
```

#Add Before.After
```{r}
filter_fish$real_datetime <- parse_date_time(filter_fish$real_datetime, orders = "ymd HMS")
heatwave_date_start <- parse_date_time("02-07-2017 00:00:00",orders = "dmy HMS")
heatwave_date_end <- parse_date_time("16-07-2017 00:00:00",orders = "dmy HMS")
filter_fish$Before_After <- ifelse(filter_fish$real_datetime < heatwave_date_start,"Before",ifelse(filter_fish$real_datetime > heatwave_date_end,"After","MHW"))
for (row_num in 342534:dim(filter_fish)[1]) {
# filter_fish$Day_night[row_num] <- ifelse(filter_fish$real_datetime[row_num] > filter_fish$sunrise[row_num] && filter_fish$real_datetime[row_num] < filter_fish$sunset[row_num],"Day","Night")
  if(filter_fish$Before_After[row_num]=="Before")
  {
    filter_fish$Before_After_continiuos[row_num] <- 
      difftime(filter_fish$real_datetime[row_num],heatwave_date_start,units = "days")
  } else if(filter_fish$Before_After[row_num]=="After")
  {
    filter_fish$Before_After_continiuos[row_num] <- 
      difftime(filter_fish$real_datetime[row_num],heatwave_date_end,units = "days")
  }
  else
  {
    filter_fish$Before_After_continiuos[row_num] <- 0
  }

}
```

##Calculate longshore_movement
```{r}
for (fish in valuble_fish) {
  temp_fish <- filter_fish %>% filter(fish_id==fish)
  #get the northest position to standerize movement to
  northest_position <- min(temp_fish$distance_shore)
  temp_fish$longshore_movement <- temp_fish$distance_shore-northest_position
  temp_fish <- temp_fish %>% select(real_datetime,fish_id,longshore_movement)
  filter_fish[filter_fish$real_datetime==temp_fish$real_datetime & filter_fish$fish_id==temp_fish$fish_id] <- merge(filter_fish,temp_fish,all.x = T,by = c("real_datetime","fish_id"))
}
```


#save data
```{r}
write.csv(filter_fish,"Valuble_fish_before_after.csv")
saveRDS(filter_fish,"Valuble_fish.RDS")
```

##Cut data to the time of the MHW
```{r}
MHW_Data <- filter_fish[filter_fish$Before_After_continiuos>-60 & filter_fish$Before_After_continiuos<60,]
MHW_Data <- MHW_Data %>% arrange(fish_id,real_datetime)
date_sun_df <- data.frame(date=as.Date(unique(MHW_Data$date)),
                          lat=29.538417,
                          lon=34.954417)
date_sun_df <- getSunlightTimes(data = date_sun_df,
                               keep = c("sunrise","sunriseEnd","solarNoon","sunsetStart","sunset","night","nadir"),tz="Asia/Jerusalem")
date_sun_df[,4:10] <- force_tz(date_sun_df[,4:10],tz="UTC")
write.csv(MHW_Data,"Eilat_2017_MHW_Fish_Data.csv")

```

##Calculate means before and after the heat wave 
```{r}
#total means
sum_heat_wave <- MHW_Data %>% group_by(fish_id,Before_After,period_of_day) %>% 
  summarise_at(vars(activity,depth,distance_shore),funs(mean(.,na.rm=T), median(.,na.rm=T), sd(.,na.rm=T),
                                                        n())) %>%
  mutate(Conf_int_activity=activity_sd/sqrt(activity_n) * qt(p=0.975,df=activity_n-1),
         Conf_int_depth=depth_sd/sqrt(depth_n) * qt(p=0.975,df=depth_n-1),
         Conf_int_distance_shore=distance_shore_sd/sqrt(distance_shore_n) *
           qt(p=0.975,df=distance_shore_n-1))
write.csv(sum_heat_wave,"sum_heatwave_by_fish_before_after.csv")
sum_before_after <- sum_heat_wave %>% group_by(Before_After,period_of_day) %>% 
  summarise_at(vars(activity_mean,depth_mean,distance_shore_mean),funs(mean(.,na.rm=T),sd(.,na.rm=T),n())) %>% mutate(Conf_int_activity=activity_mean_sd/sqrt(activity_mean_n) * qt(p=0.975,df=activity_mean_n-1),
         Conf_int_depth=depth_mean_sd/sqrt(depth_mean_n) * qt(p=0.975,df=depth_mean_n-1),
         Conf_int_distance_shore=distance_shore_mean_sd/sqrt(distance_shore_mean_n) *
           qt(p=0.975,df=distance_shore_mean_n-1))
write.csv(sum_before_after,"sum_heatwave_before_after.csv")
```


#Graphs
```{r}
#activity
for (period in unique(MHW_Data$period_of_day)) {
 activity_plot <- ggplot(MHW_Data[MHW_Data$period_of_day==period,],aes(x=Before_After,y=activity))+
  geom_point(size=0.3,color="black",alpha=0.5)+
  geom_vline(xintercept = 0,color="red")+
  # scale_x_datetime(date_breaks = "7 days",date_labels = "%d/%m/%y")+
  geom_smooth(color="blue")+
  facet_wrap(~fish_id,ncol=1)+
   theme_bw()+
   theme(panel.grid.major = element_blank(),
         panel.grid.minor = element_blank(),
         panel.background = element_blank(),
         legend.position="none")
 depth_plot <- ggplot(MHW_Data[MHW_Data$period_of_day==period,],aes(x=Before_After,y=depth))+
  geom_point(size=0.3,color="black",alpha=0.5)+
  geom_vline(xintercept = 0,color="red")+
  # scale_x_datetime(date_breaks = "7 days",date_labels = "%d/%m/%y")+
  geom_smooth(color="darkgreen")+
  facet_wrap(~fish_id,ncol=1)+
   theme_bw()+
   theme(panel.grid.major = element_blank(),
         panel.grid.minor = element_blank(),
         panel.background = element_blank(),
         legend.position="none")
 longshore_plot <- ggplot(MHW_Data[MHW_Data$period_of_day==period,],aes(x=Before_After,y=distance_shore))+
  geom_point(size=0.3,color="black",alpha=0.5)+
  geom_vline(xintercept = 0,color="red")+
  # scale_x_datetime(date_breaks = "7 days",date_labels = "%d/%m/%y")+
  geom_smooth(color="gold")+
  facet_wrap(~fish_id,ncol=1)+
   theme_bw()+
   theme(panel.grid.major = element_blank(),
         panel.grid.minor = element_blank(),
         panel.background = element_blank(),
         legend.position="none")
 comibne_plot <- activity_plot+depth_plot+longshore_plot
ggsave(paste("Before_After_plot_",period,".png"),width = 4500,height = 10000,units = "px") 
}
 

```